
// This file has been generated by the GUI designer. Do not modify.
namespace SCTIGR
{
	public partial class MainForm
	{
		private global::Gtk.ScrolledWindow scrolledwindow2;

		private global::SCTIGR.ProfileControl profilecontrol1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget SCTIGR.MainForm
			this.Name = "SCTIGR.MainForm";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainForm");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child SCTIGR.MainForm.Gtk.Container+ContainerChild
			this.scrolledwindow2 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow2.CanFocus = true;
			this.scrolledwindow2.Name = "scrolledwindow2";
			this.scrolledwindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow2.Gtk.Container+ContainerChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport ();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.profilecontrol1 = new global::SCTIGR.ProfileControl ();
			this.profilecontrol1.Events = ((global::Gdk.EventMask)(256));
			this.profilecontrol1.Name = "profilecontrol1";
			w1.Add (this.profilecontrol1);
			this.scrolledwindow2.Add (w1);
			this.Add (this.scrolledwindow2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 613;
			this.DefaultHeight = 410;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.OnKeyPressEvent);
		}
	}
}
