
// This file has been generated by the GUI designer. Do not modify.
namespace SCTIGR
{
	public partial class ProfileControl
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget SCTIGR.ProfileControl
			global::Stetic.BinContainer.Attach (this);
			this.Name = "SCTIGR.ProfileControl";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
