
// This file has been generated by the GUI designer. Do not modify.
namespace SCTIGR
{
	public partial class SequenceControl
	{
		private global::Gtk.Label label;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget SCTIGR.SequenceControl
			global::Stetic.BinContainer.Attach (this);
			this.Name = "SCTIGR.SequenceControl";
			// Container child SCTIGR.SequenceControl.Gtk.Container+ContainerChild
			this.label = new global::Gtk.Label ();
			this.label.Name = "label";
			this.label.Xalign = 0f;
			this.label.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.label.UseMarkup = true;
			this.label.WidthChars = 0;
			this.Add (this.label);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
