
// This file has been generated by the GUI designer. Do not modify.
namespace SCTIGR
{
	public partial class SequencesList
	{
		private global::Gtk.VBox vbox3;

		private global::Gtk.VBox vbox;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget SCTIGR.SequencesList
			global::Stetic.BinContainer.Attach (this);
			this.Name = "SCTIGR.SequencesList";
			// Container child SCTIGR.SequencesList.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.vbox = new global::Gtk.VBox ();
			this.vbox.Name = "vbox";
			this.vbox.Spacing = 6;
			this.vbox3.Add (this.vbox);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.vbox]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
